version: 2.1

orbs:
  onepassword: onepassword/secrets@1.0.0
  # slack: circleci/slack@4.13.3
  azure-cli: circleci/azure-cli@1.2.2
  node: circleci/node@7.1.0

parameters:
  # Slack params
  slack_branch:
    default: "main"
    type: string
  slack_channel_failure:
    default: "#bot-circleci-builds"
    type: string
  slack_channel_success:
    default: "#bot-circleci-builds"
    type: string
  addon_name:
    type: string
    default: "Genvid_Marketplace"
  node_version:
    type: string
    default: "22.14"
  onepassword_version:
    type: string
    default: "2.29.0"

commands:
  az-login:
    steps:
      - run:
          name: Login to Azure
          command: |
            az login \
              --service-principal \
              --username=${AZURE_SP_APPID} \
              --tenant=${AZURE_SP_TENANT} \
              --password=${AZURE_SP_PASSWORD}

jobs:
  packages:
    parameters:
      onepassword-env:
        type: string
        default: '/tmp/op.env'
    docker:
      - image: cimg/node:<< pipeline.parameters.node_version >>
    shell: op run --env-file="<< parameters.onepassword-env >>" -- /bin/bash -eo pipefail
    steps:
      - onepassword/install-cli:
          shell: /bin/bash -eo pipefail
          version: << pipeline.parameters.onepassword_version >>
      - run:
          shell: /bin/bash -eo pipefail
          name: Setup secret environment and read from OnePassword
          command: |
            echo "Reading OnePassword environment file..."
            op read "op://${BURBANK_ENV_FILE}" -o << parameters.onepassword-env >>
      - checkout
      - azure-cli/install
      - az-login
      - node/install-packages:
          # Override to use cache
          override-ci-command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: |
            npm run build
            npm run zip:posix
      - store_artifacts:
          path: << pipeline.parameters.addon_name >>.c3addon
      - run:
          name: Upload to Azure
          command: |
            TAG=<< pipeline.git.tag >>
            BRANCH=<< pipeline.git.branch >>
            if [ -z "${TAG}" ] ; then
              export SLUG=branch/${BRANCH}
            else
              export SLUG=tags/${TAG}
            fi

            az storage blob upload \
              --overwrite \
              -c 'c3addons' \
              -n "${CIRCLE_PROJECT_REPONAME}/${SLUG}/<< pipeline.parameters.addon_name >>.c3addon" \
              --file << pipeline.parameters.addon_name >>.c3addon


workflows:
  default:
    jobs:
      - packages:
          filters:
            tags:
              # Only tags starting with at least one or more digits followed by a dot
              only: /\d+\..*/
          context:
            - burbank-onepassword
